### ISSUE TITLE
Bitte an die offiziellen Oracle Java Konventionen halten

### ISSUE THREAD

**Issue by Fridious** [FHDW-23SS-SMA-IFWS421B/BonnYPJ#1]
![image](https://github.com/FHDW-23SS-SMA-IFWS421B/BonnYPJ/assets/40139474/9678d04a-0a8d-4e10-87e2-fd7ffc6ac164)

**Comment by Florianxr68** [comment]
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf
